/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader"

type GLTFResult = GLTF & {
    nodes: {
        Cube001: THREE.Mesh
        Cube009: THREE.Mesh
        Vert003: THREE.Mesh
        Laptop: THREE.Mesh
        Cube005: THREE.Mesh
        Cube007: THREE.Mesh
        Cube002: THREE.Mesh
        Cube003: THREE.Mesh
        Cube004: THREE.Mesh
        Cube006: THREE.Mesh
        Cube008: THREE.Mesh
        Cube: THREE.Mesh
        pencil: THREE.Mesh
        tabletop001: THREE.Mesh
        Plane: THREE.Mesh
        Plane001: THREE.Mesh
        Plane002: THREE.Mesh
        Plane003: THREE.Mesh
        Vert: THREE.Mesh
        Circle001: THREE.Mesh
        Vert001: THREE.Mesh
        monstera_leaf005: THREE.Mesh
        monstera_leaf002: THREE.Mesh
        monstera_leaf003: THREE.Mesh
        monstera_leaf004: THREE.Mesh
        monstera_leaf006: THREE.Mesh
        monstera_leaf007: THREE.Mesh
        Vert002: THREE.Mesh
        Circle: THREE.Mesh
        NurbsPath: THREE.Mesh
        NurbsPath001: THREE.Mesh
        NurbsPath003: THREE.Mesh
        NurbsPath005: THREE.Mesh
        NurbsPath002: THREE.Mesh
        NurbsPath006: THREE.Mesh
        NurbsPath004: THREE.Mesh
        NurbsPath007: THREE.Mesh
        mug: THREE.Mesh
        Circle002: THREE.Mesh
        Cube010_1: THREE.Mesh
    }
    materials: {
        ["default"]: THREE.MeshStandardMaterial
        ["Material.007"]: THREE.MeshStandardMaterial
        ["Material.005"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["Material.006"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        Material: THREE.MeshStandardMaterial
        ["Material.003"]: THREE.MeshStandardMaterial
        ["Material.008"]: THREE.MeshStandardMaterial
        ["Material.004"]: THREE.MeshStandardMaterial
        ["Material.001"]: THREE.MeshStandardMaterial
        ["default"]: THREE.MeshStandardMaterial
        ["Material.002"]: THREE.MeshStandardMaterial
    }
}

export default function HomeSection1Model(
    props: JSX.IntrinsicElements["group"]
) {
    const group = useRef<THREE.Group>()
    const { nodes, materials } = useGLTF("/modelDraco2.gltf") as GLTFResult
    return (
        <group ref={group} {...props} dispose={null}>
            <group userData={{ name: "tabletop" }}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001.geometry}
                    material={nodes.Cube001.material}
                    position={[-0.86, -0.06, -0.48]}
                    rotation={[-Math.PI, -1.57, 0]}
                    scale={0.04}
                    userData={{ name: "Cube.001" }}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube009.geometry}
                material={materials["Material.007"]}
                position={[0.4, 0.13, 0.08]}
                rotation={[0, 0, 0.22]}
                userData={{ name: "Cube.009" }}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Vert003.geometry}
                material={materials["Material.005"]}
                position={[0.4, 0.03, 0]}
                userData={{ name: "Vert.003" }}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Laptop.geometry}
                material={nodes.Laptop.material}
                position={[0, 0, 0.17]}
                rotation={[-Math.PI, 0, -Math.PI]}
                userData={{ name: "Laptop" }}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005.geometry}
                    material={nodes.Cube005.material}
                    position={[0.21, 0.07, 0.11]}
                    rotation={[3.08, 0, -Math.PI]}
                    scale={[0.01, 0.01, 0.01]}
                    userData={{ name: "Cube.005" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube007.geometry}
                    material={nodes.Cube007.material}
                    position={[0.21, 0.07, 0.11]}
                    rotation={[3.08, 0, -Math.PI]}
                    scale={[0.01, 0.01, 0.01]}
                    userData={{ name: "Cube.007" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002.geometry}
                    material={nodes.Cube002.material}
                    position={[0, 0.23, 0.18]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    userData={{ name: "Cube.002" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003.geometry}
                    material={nodes.Cube003.material}
                    position={[0, -0.2, 0]}
                    userData={{ name: "Cube.003" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004.geometry}
                    material={materials["Material.006"]}
                    position={[0, 0.23, 0.18]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    userData={{ name: "Cube.004" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube006.geometry}
                    material={nodes.Cube006.material}
                    position={[0.21, 0.07, 0.11]}
                    rotation={[3.08, 0, -Math.PI]}
                    scale={[0.01, 0.01, 0.01]}
                    userData={{ name: "Cube.006" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube008.geometry}
                    material={nodes.Cube008.material}
                    position={[0.21, 0.07, 0.11]}
                    rotation={[3.08, 0, -Math.PI]}
                    scale={[0.01, 0.01, 0.01]}
                    userData={{ name: "Cube.008" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube.geometry}
                    material={nodes.Cube.material}
                    position={[0.21, 0.07, 0.11]}
                    rotation={[3.08, 0, -Math.PI]}
                    scale={[0.01, 0.01, 0.01]}
                    userData={{ name: "Cube" }}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pencil.geometry}
                material={nodes.pencil.material}
                position={[-0.29, 0.04, 0.06]}
                rotation={[Math.PI, -1.3, Math.PI / 2]}
                scale={0.01}
                userData={{ name: "pencil" }}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.tabletop001.geometry}
                material={nodes.tabletop001.material}
                userData={{ name: "tabletop.001" }}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                material={nodes.Plane.material}
                position={[-0.58, 0.16, 0.23]}
                rotation={[Math.PI / 2, 0, -0.61]}
                scale={[0.13, 0.13, 0.13]}
                userData={{ name: "Plane" }}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001.geometry}
                material={nodes.Plane001.material}
                position={[-0.58, 0.16, 0.23]}
                rotation={[Math.PI / 2, 0, -0.61]}
                scale={0.13}
                userData={{ name: "Plane.001" }}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002.geometry}
                material={nodes.Plane002.material}
                position={[-0.58, 0.16, 0.23]}
                rotation={[Math.PI / 2, 0, -0.61]}
                scale={[0.13, 0.13, 0.13]}
                userData={{ name: "Plane.002" }}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane003.geometry}
                material={nodes.Plane003.material}
                position={[-0.58, 0.16, 0.23]}
                rotation={[Math.PI / 2, 0, -0.61]}
                scale={[0.13, 0.13, 0.13]}
                userData={{ name: "Plane.003" }}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Vert.geometry}
                material={nodes.Vert.material}
                position={[-0.51, 0.03, -0.29]}
                scale={0.26}
                userData={{ name: "Vert" }}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle001.geometry}
                    material={nodes.Circle001.material}
                    position={[0, 0.66, 0]}
                    scale={2.49}
                    userData={{ name: "Circle.001" }}
                >
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Vert001.geometry}
                        material={nodes.Vert001.material}
                        position={[0, 0.01, 0]}
                        scale={1.55}
                        userData={{ name: "Vert.001" }}
                    >
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.monstera_leaf005.geometry}
                            material={nodes.monstera_leaf005.material}
                            position={[-0.01, 0.34, 0.07]}
                            rotation={[0.61, -0.57, 0.43]}
                            scale={[0.1, 0.1, 0.1]}
                            userData={{ name: "monstera leaf.005" }}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.monstera_leaf002.geometry}
                            material={nodes.monstera_leaf002.material}
                            position={[0.1, 0.44, -0.08]}
                            rotation={[2.68, -0.13, -2.92]}
                            scale={[0.1, 0.1, 0.1]}
                            userData={{ name: "monstera leaf.002" }}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.monstera_leaf003.geometry}
                            material={nodes.monstera_leaf003.material}
                            position={[0.16, 0.41, 0.06]}
                            rotation={[0.13, -0.02, -0.31]}
                            scale={[0.13, 0.13, 0.13]}
                            userData={{ name: "monstera leaf.003" }}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.monstera_leaf004.geometry}
                            material={nodes.monstera_leaf004.material}
                            position={[-0.12, 0.19, -0.03]}
                            rotation={[1.81, -0.44, 1.23]}
                            scale={[0.1, 0.1, 0.1]}
                            userData={{ name: "monstera leaf.004" }}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.monstera_leaf006.geometry}
                            material={nodes.monstera_leaf006.material}
                            position={[-0.06, 0.37, -0.05]}
                            rotation={[1.81, -1.01, 2.18]}
                            scale={[0.07, 0.07, 0.07]}
                            userData={{ name: "monstera leaf.006" }}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.monstera_leaf007.geometry}
                            material={nodes.monstera_leaf007.material}
                            position={[0.02, 0.11, -0.11]}
                            rotation={[2.41, 0.2, -2.61]}
                            scale={[0.07, 0.07, 0.07]}
                            userData={{ name: "monstera leaf.007" }}
                        />
                    </mesh>
                </mesh>
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Vert002.geometry}
                material={nodes.Vert002.material}
                position={[0.68, 0.02, -0.31]}
                userData={{ name: "Vert.002" }}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle.geometry}
                    material={nodes.Circle.material}
                    position={[0, 0.07, 0]}
                    scale={0.06}
                    userData={{ name: "Circle" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NurbsPath.geometry}
                    material={nodes.NurbsPath.material}
                    position={[0, 0.07, -0.01]}
                    rotation={[2.22, -Math.PI / 2, 0]}
                    scale={[0.74, 0.74, 0.74]}
                    userData={{ name: "NurbsPath" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NurbsPath001.geometry}
                    material={nodes.NurbsPath001.material}
                    position={[0.01, 0.07, 0]}
                    rotation={[-Math.PI, -1, 0.92]}
                    scale={[0.98, 0.98, 0.98]}
                    userData={{ name: "NurbsPath.001" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NurbsPath003.geometry}
                    material={nodes.NurbsPath003.material}
                    position={[-0.02, 0.07, 0]}
                    rotation={[0, 0.88, -2.22]}
                    scale={[0.91, 0.91, 0.91]}
                    userData={{ name: "NurbsPath.003" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NurbsPath005.geometry}
                    material={nodes.NurbsPath005.material}
                    position={[0.02, 0.07, 0.01]}
                    rotation={[-Math.PI, -0.25, 0.92]}
                    scale={[0.68, 0.68, 0.68]}
                    userData={{ name: "NurbsPath.005" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NurbsPath002.geometry}
                    material={nodes.NurbsPath002.material}
                    position={[-0.02, 0.07, -0.01]}
                    rotation={[0, -0.29, -2.22]}
                    scale={[0.98, 0.98, 0.98]}
                    userData={{ name: "NurbsPath.002" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NurbsPath006.geometry}
                    material={nodes.NurbsPath006.material}
                    position={[-0.01, 0.07, 0.02]}
                    rotation={[-Math.PI, 1.5, 0.92]}
                    scale={[0.57, 0.57, 0.57]}
                    userData={{ name: "NurbsPath.006" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NurbsPath004.geometry}
                    material={nodes.NurbsPath004.material}
                    position={[0, 0.07, 0.01]}
                    rotation={[-Math.PI, 0.51, 0.92]}
                    scale={0.88}
                    userData={{ name: "NurbsPath.004" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.NurbsPath007.geometry}
                    material={nodes.NurbsPath007.material}
                    position={[-0.01, 0.07, 0]}
                    rotation={[0, 0.32, -2.22]}
                    scale={[0.91, 0.91, 0.91]}
                    userData={{ name: "NurbsPath.007" }}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mug.geometry}
                material={nodes.mug.material}
                position={[0.7, 0.03, 0.15]}
                rotation={[-Math.PI, 1.21, -Math.PI]}
                scale={[0.98, 0.98, 0.98]}
                userData={{ name: "mug" }}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle002.geometry}
                    material={materials["Material.002"]}
                    position={[0, 0.07, 0]}
                    scale={0.04}
                    userData={{ name: "Circle.002" }}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube010_1.geometry}
                    material={nodes.Cube010_1.material}
                    userData={{ name: "Cube.010" }}
                />
            </mesh>
        </group>
    )
}

useGLTF.preload("/modelDraco2.gltf")
