import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "@styles/Home.module.css"
import { useEffect, useRef } from "react"
import { useThree } from "@hooks/useThree"

const Home: NextPage = () => {
    const threeCanvasRef = useRef<HTMLDivElement>(null)

    const [threeBasics, renderOptions] = useThree(threeCanvasRef)

    useEffect(() => {
        renderOptions.start()

        setTimeout(() => {
            renderOptions.stop()
        }, 3000)

        return () => {
            renderOptions.stop()
        }
    }, [threeBasics])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${styles.main} bg-red-400`}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <div
                    className="threeCanvas"
                    ref={threeCanvasRef}
                    style={{ width: "50em", height: "30em" }}
                ></div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
